erdewit/ib_insync

- notebooks/bar_data.ipynb
- notebooks/market_depth.ipynb
- notebooks/tick_data.ipynb
These appear to have gotten lost from an earlier version.
> Fix missing import of IPython.display.display

- ib_insync/wrapper.py
Proposed fix for the issue #36.
Not completely sure if this patch breaks something else, but I verified, it does solve the issue with my TradeLogIB script and partially filled multi-leg option orders. See issue description for more details.
> ib.fills() returns incorrect results for partially filled orders for multi-leg option COMBO trades #36

- ib_insync/ib.py
Fixes: 
```python
--> 661                 self.orderCancelEvent.emit(trade)
662                 self.orderStatusEvent.emit(trade)
663         else:
AttributeError: 'IB' object has no attribute 'orderCancelEvent'
```
I went with this naming because it's what's already in the doc and in the events list.
> Fix misnamed event

- ib_insync/ib.py
Fixed typo in docs of reqHistoricalData method.
Removed 's' from durationStr in description of arguments.
> Typo Correction

- ib_insync/ib.py
- ib_insync/ticker.py
- ib_insync/wrapper.py
* Handle tickType 34, 35, 36 in wrapper
* Assign default ``nan`` for  ``auctionVolume``, ``auctionPrice``, ``auctionImbalance`` in  ``ticker`` class.
* Document ``auctionVolume``, ``auctionPrice``, ``auctionImbalance`` as return of genericTick 225 (https://interactivebrokers.github.io/tws-api/tick_types.html)
> Handle tickTypes related to auctions

- ib_insync/util.py
Scheduling callbacks using util.schedule should return the Event Handle (that is always returned from asyncio when scheduling).
This can be used to cancel scheduled callbacks.
For example, when the watchdog emit the stopped event and there are scheduled jobs that requires connected ib.
> Util schedule: return Events Handle.

- ib_insync/ibcontroller.py
According to IB, on error 100 
> The TWS will likely disconnect the client application after this message.
The watchdog can't detect the client disconnection in this scenario,
As it won't be followed with error 1100, and the disconnect event wont fire.
Links:
[IB error codes](https://interactivebrokers.github.io/tws-api/message_codes.html)
[Example case](https://groups.io/g/insync/topic/max_rate_of_messages/6390099?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,6390099)
> watchdog: restart on error 100

- ib_insync/ib.py
Usage: ib.connect('127.0.0.1', 1234, clientId=1, timeout=360, account='U1234567')
This is necessary when working with >1 accounts.
For example, let's say I have both a regular (U0000001) and an IRA (U0000002) accounts with IB. Let's say I call ib.connect(...) to trade using U0000002 in my IRA. When called, ib.connect() configures portfolio updates for the default account U0000001. So next, I have to call ib.reqAccountUpdates(account='U0000002') to get portfolio updates for U0000002.
Next, say I want to download history while the trading code trades. I launch another Python code to access API for account U0000002. That code calls ib.connect() and now ib.connect() *fails* because the trading code is getting portfolio updates (or feed) for account U0000002, but ib.connect() in my history …
> Pass account name to ib.connect()

- ib_insync/__init__.py
- ib_insync/contract.py
- ib_insync/ib.py
- ib_insync/objects.py
- ib_insync/order.py
- ib_insync/ticker.py
- ib_insync/util.py
- mypy.ini
- setup.py
Though there are still more annotations that could be added, this PR introduces the minimal number of type annotations that completely pass `mypy` on the default settings, as tested with:
```sh
mypy -p ib_insync
```
This required some fixes to existing type signatures in the `ib` and `util` modules—e.g., for [arbitrary argument lists](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values) or `async def` functions (which I can't find clear documentation for, but in practice should not be annotated to return `Awaitable`, as it's inferred).
Resolves #203.
> Adding more typing annotations to external APIs

- ib_insync/ibcontroller.py
I'd like to use `readonly` option of ib.connect/ib.connectAsync with Watchdog.
> add readonly option for Watchdog

- ib_insync/ib.py
- ib_insync/wrapper.py
When a request fails, say, `orderWhatIf()` due to running in read-only mode, presently this is not propagated back to the caller. Instead she receives an empty list (which isn't even the correct type), and the true error is buried in the logs.
No doubt users (just like me) have code that relies on the old behaviour, so it wouldn't be a good idea to change without a version bump, so instead expose a new `IB(quash_errors=False)` constructor parameter that instead causes an exception to be propagated to pending futures where possible.
I did not regenerate the docs in this PR because I couldn't get the Sphinx config to match whatever setup was used to generate the checked in docs.
> Add ib_insync.wrapper.RequestError and optionally raise it

- ib_insync/wrapper.py
In a prior commit it seems that similar functionality was removed (https://github.com/erdewit/ib_insync/commit/e23e6ff52c12b54b795767cb1d5e9705a9b797d4). I am not sure of why - therefore I propose this change.
1) Create order of e.g. quantity 1000
2) Resize it to quantity 1100
3) List all open orders using `ib.openTrades()` - there it will still have totalQuantity 1000. But orderStatus.remaining will be 1100 and it will be 1100 in IB TWS. 
Similarly for price changes.
> Update quantity/price in wrapper.openOrder()

- docs/recipes.rst
The DataFrame has a index by default, and when `.to_csv` is called, the first column in the csv file is the index, and there is no header for that column. It makes the csv not able to be parsed by other program. Example data is like
```
,date,open,high,low,close,volume,average,barCount
0,2020-10-16 10:40:00,3476.25,3476.25,3476.25,3476.25,1,3476.25,1
1,2020-10-16 10:41:00,3476.75,3476.75,3476.75,3476.75,1,3476.75,1
2,2020-10-16 10:42:00,3476.75,3476.75,3476.75,3476.75,0,3476.75,0
3,2020-10-16 10:43:00,3475.75,3475.75,3475.75,3475.75,5,3475.75,3
4,2020-10-16 10:44:00,3475.75,3475.75,3475.75,3475.75,0,3475.75,0
5,2020-10-16 10:45:00,3475.75,3475.75,3475.75,3475.75,0,3475.75,0
6,2020-10-16 10:46:00,3475.75,3475.75,3475.75,3475.75,0,3475.75,0
7,2020-10-16 …
```
> remove the index of DataFrame before write to CSV

- ib_insync/ib.py
IBKR exposes the "daytrades remaining" counter as up to 5 values: one for
the current day, then more individual counts for 4 future days when the
limits will increase again.
> Add summary request for future daily day trade limits

- ib_insync/decoder.py
- ib_insync/ticker.py
- ib_insync/wrapper.py
- Added support for displaying the bid and ask exchanges as provided by tick types 32 and 33 [here](https://interactivebrokers.github.io/tws-api/tick_types.html)
- The resulting string of capital letters _appears_ to follow the exchange codes found [here](https://tlc.thinkorswim.com/center/howToTos/thinkManual/Miscellaneous/Exchange-Codes)
- The goal is to be able to decode the exchanges using reqSmartComponents(), though this commit merely adds the encoded exchange sequences to the ticker objects.
This commit passed 100% of the tests.
I appreciate any feedback.
> added support for bidExchange and askExchange

- ib_insync/ibcontroller.py
The purpose of this change is to be able to await the runAsync future completion external to watchdog.
Without awaiting for the runAsync task to complete the "finally" part of the function is not executed following `watchdog.stop()`, `onDisconnected`, and `waiter.set_exception(Warning('Disconnected'))` resulting in IB_Gateway instance running without proper termination.
An alternative to this change would be to await for the runAsync task to complete internally to the watchdog class - but that would involve rework of the while loop dependency on the `self._runner = None` and/or keeping the runAsync task reference in a separate variable that would be awaited in `watchdog.stop()`.
> watchdog.start() return runAsync future

- ib_insync/decoder.py
Missing '*fields' to collect additional fields on bondContractDetails.
Without the proposed patch bondContractDetails() fails with current server versions
> missing '*fields' on bondContractDetails

- ib_insync/ticker.py
Ticker object has two useful filters based on time and number of ticks. I often use bars based on fixed volume and thought it would be nice to have this option included as standard as well. This type of bars is often include in literature, e.g. M. Lopez de Prado 'Advances in Financial Machine Learning' 2018, p. 27
> volume ticker

- docs/conf.py
- docs/html/_modules/ib_insync/client.html
- docs/html/_modules/ib_insync/contract.html
- docs/html/_modules/ib_insync/flexreport.html
- docs/html/_modules/ib_insync/ib.html
- docs/html/_modules/ib_insync/ibcontroller.html
- docs/html/_modules/ib_insync/objects.html
- docs/html/_modules/ib_insync/order.html
- docs/html/_modules/ib_insync/ticker.html
- docs/html/_modules/ib_insync/util.html
- docs/html/_modules/ib_insync/wrapper.html
- docs/html/_modules/index.html
- docs/html/api.html
- docs/html/changelog.html
- docs/html/code.html
- docs/html/genindex.html
- docs/html/index.html
- docs/html/links.html
- docs/html/notebooks.html
- docs/html/py-modindex.html
- docs/html/readme.html
- docs/html/recipes.html
- docs/html/search.html
- ib_insync/objects.py
- ib_insync/wrapper.py
Small fix: updated the year 2022 to the current year 2023 in all the docs. 
Updated the broken link for Fundamental Ratios(deprecated) with archive(.)org snapshot link #587
> updated the year to current year in docs and fundamental ratios link 

- ib_insync/ib.py
default is `False` to preserve the current behaviour
> add option to raise on sync failures on connect
